#ifndef __DDIL_EXTKEY_CONFIG_H_
#define __DDIL_EXTKEY_CONFIG_H_
#include "DDIL_ErrorCode.h"

/*设备数量*/
#define DDIL_EXTKEY_NUM      1

/*设备ID号枚举*/
typedef enum DDIL_EXTKEY_INDEX
{
    DDIL_EXTKEY_INDEX_0 = 0,
}DDIL_EXTKEY_INDEX;

/*EXTKEY状态枚举*/
typedef enum DDIL_EXTKEY_STATUS
{
    DDIL_EXTKEY_STATUS_NONE = 0,
    DDIL_EXTKEY_STATUS_1 = 1,
    DDIL_EXTKEY_STATUS_2 = 2,
    DDIL_EXTKEY_STATUS_3 = 3,
    DDIL_EXTKEY_STATUS_4 = 4,
    DDIL_EXTKEY_STATUS_5 = 5,
    DDIL_EXTKEY_STATUS_6 = 6,
    DDIL_EXTKEY_STATUS_7 = 7,
    DDIL_EXTKEY_STATUS_8 = 8,
    DDIL_EXTKEY_STATUS_9 = 9,
    DDIL_EXTKEY_STATUS_10 = 10,
    DDIL_EXTKEY_STATUS_11 = 11,
    DDIL_EXTKEY_STATUS_12 = 12,
    DDIL_EXTKEY_STATUS_13 = 13,
    DDIL_EXTKEY_STATUS_14 = 14,
    DDIL_EXTKEY_STATUS_15 = 15,
    DDIL_EXTKEY_STATUS_16 = 16,
}DDIL_EXTKEY_STATUS;


#include "ExtKey.h"
#include "DDIL_ExtKey.h"

#endif